In [5]:
import numpy as np

input_dim = 2
hidden_dim = 3
W1 = np.random.normal(0, 1, input_dim * hidden_dim).reshape((input_dim, hidden_dim))
print(W1)
b1 = np.zeros(hidden_dim)
print(b1)
print(b1.shape)

[[ 1.05101991  0.00277375  1.88719488]
 [-1.07404317  0.49688698  1.77904649]]
[ 0.  0.  0.]
(3,)
